// Module key
const KEY_MODULE = '[PRODUCT]: ';

export const ADD_PRODUCT = `${KEY_MODULE} ADD_PRODUCT`;
export const DELETE_PRODUCT = `${KEY_MODULE} DELETE_PRODUCT`;
export const UPDATE_PRODUCT = `${KEY_MODULE} UPDATE_PRODUCT`;